Repository nextcloud/announcementcenter, pull requests merged in 2021-09, with the labels that each got.

#388 Fix CI
  .github/workflows/phpunit.yml
Labels: 4. to release, backport-request

#389 Fix CI
  .github/workflows/phpunit.yml
Labels: 4. to release

#390 Fix CI
  .github/workflows/phpunit.yml
Labels: 4. to release

#391 Fix "Route does not exist"
  lib/Dashboard/Widget.php
Labels: bug, 3. to review, backport-request

#394 Fixed the case when multiple announcements are added for the same gro…
  lib/BackgroundJob.php
Labels: 3. to review, backport-request

#398 Add changelog for 4.0.2, 5.0.1 and 6.0.0
  CHANGELOG.md
Labels: backport-request
