Repository nextcloud/announcementcenter, pull requests merged in 2021-06, with the labels that each got.

#357 Bump deps
  .eslintrc.js
  .gitattributes
  babel.config.js
  js/announcementcenter-admin.js
  js/announcementcenter-admin.js.LICENSE.txt
  js/announcementcenter-admin.js.map
  js/announcementcenter-dashboard.js.LICENSE.txt
  js/announcementcenter-main.js.LICENSE.txt
  package-lock.json
  package.json
  src/admin.js
  templates/admin.php
  webpack.js
Labels: 3. to review, dependencies

#361 Bump phpunit, add psalm, dump app:code-check
  .github/workflows/app-code-check.yml
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  lib/Activity/Provider.php
  lib/AppInfo/Application.php
  lib/BackgroundJob.php
  lib/Controller/APIController.php
  lib/Controller/PageController.php
  lib/Dashboard/Widget.php
  lib/Manager.php
  lib/Model/Announcement.php
  lib/Model/GroupMapper.php
  lib/Notification/Notifier.php
  psalm.xml
  tests/BackgroundJobTest.php
  tests/Notification/NotifierTest.php
  tests/psalm-baseline.xml
Labels: 4. to release, technical debt

#364 Don't open sidebar without comments being enabled
  src/Components/Announcement.vue
Labels: 3. to review, bug, feature: comments 💬
