Repository nextcloud/announcementcenter, pull requests merged in 2022-08, with the labels that each got.

#500 Fix "Skip to content" and "Unique headlines" for accessibility
  lib/Controller/PageController.php
  src/App.vue
Labels: bug, 3. to review, feature: announcements 🗣️

#501 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#513 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#515 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#519 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
