Repository nextcloud/announcementcenter, pull requests merged in 2022-10, with the labels that each got.

#533 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#547 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: dependencies

#548 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#550 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#551 Skip users without a valid email address
  lib/BackgroundJob.php
  tests/BackgroundJobTest.php
Labels: backport-request

#556 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
