Repository nextcloud/announcementcenter, pull requests merged in 2023-01, with the labels that each got.

#576 Don't load comment sidebar when the active announcement doesn't allow comments
  src/App.vue
Labels: bug, 3. to review, feature: comments 💬

#587 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#591 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#594 Migrate to split phpunit workflows
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/phpunit.yml
  composer.json
Labels: 3. to review, technical debt

#597 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#601 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
