Repository nextcloud/announcementcenter, pull requests merged in 2023-05, with the labels that each got.

#647 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#652 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#653 Remove @nextcloud/vue-richtext
  package-lock.json
  package.json
  src/Components/Announcement.vue
  src/main.js
Labels: 3. to review

#655 fix(activity): Add a migration to remove the appconfig and preferences
  CHANGELOG.md
  appinfo/info.xml
  lib/Migration/Version6006Date20230516000000.php
Labels: bug, 3. to review
