Repository nextcloud/announcementcenter, pull requests merged in 2024-07, with the labels that each got.

#817 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, dependencies, automated

#819 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#767 Schedule publishing and deletion time
  appinfo/info.xml
  lib/AnnouncementSchedulerJob.php
  lib/Controller/APIController.php
  lib/Dashboard/Widget.php
  lib/Manager.php
  lib/Migration/Version6009Date20240311074015.php
  lib/Model/Announcement.php
  lib/Model/AnnouncementMapper.php
  lib/Model/NotificationType.php
  lib/NotificationQueueJob.php
  lib/Service/AnnouncementSchedulerProcessor.php
  src/App.vue
  src/Components/Announcement.vue
  src/Components/NewForm.vue
  src/services/announcementsService.js
  tests/Activity/SettingTest.php
  tests/AnnouncementSchedulerJobTest.php
  tests/AppInfo/ApplicationTest.php
  tests/BackgroundJobTest.php
  tests/Controller/APIControllerTest.php
  tests/ManagerTest.php
  tests/Model/NotificationTypeTest.php
  tests/Service/AnnouncementSchedulerProcessorTest.php
  tests/Settings/AdminTest.php
Labels: enhancement, 3. to review, feature: announcements 🗣️, feedback-requested
