Repository nextcloud/announcementcenter, pull requests merged in 2024-03, with the labels that each got.

#764 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#769 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#774 fix(form): Fix event-trigger for searching more groups
  src/App.vue
  src/Components/NewForm.vue
  src/Components/SettingsSelectGroup.vue
Labels: bug, 3. to review

#775 fix(form): Fix accessibility label option
  src/Components/NewForm.vue
Labels: bug, 3. to review, feature: new form ➕
