Repository nextcloud/announcementcenter, pull requests merged in 2024-09, with the labels that each got.

#835 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Activity/Setting.php
  lib/Dashboard/Widget.php
  lib/Listener/CommentsEntityListener.php
  lib/Manager.php
  lib/Migration/AnnouncementsGroupsLinks.php
  lib/Migration/Version5000Date20210223091022.php
  lib/Migration/Version6003Date20220505000000.php
  lib/Model/AnnouncementMapper.php
  lib/NotificationQueueJob.php
  lib/Settings/Admin.php
  tests/AnnouncementSchedulerJobTest.php
Labels: 3. to review, dependencies

#779 Add CLI Commands
  appinfo/info.xml
  lib/Command/Announce.php
  lib/Command/AnnouncementDelete.php
  lib/Command/AnnouncementList.php
  psalm.xml
  tests/Command/AnnounceTest.php
  tests/Command/AnnouncementDeleteTest.php
  tests/Command/AnnouncementListTest.php
Labels: enhancement, 3. to review, feature: api ⚙️, feedback-requested

#845 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#840 Add CLI command to remove notifications from an announcement
  appinfo/info.xml
  lib/Command/RemoveNotifications.php
  tests/Command/RemoveNotificationsTest.php
Labels: enhancement, 3. to review, feature: administration 🙆‍
