Repository nextcloud/announcementcenter, pull requests merged in 2025-06, with the labels that each got.

#932 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#933 ci: update node.yml workflow from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies

#943 fix: leave the NcAppSidebar rendering logic to the component
  src/App.vue
Labels: bug, 3. to review

#945 refactor: use `NcDateTime` and formatting from `@nextcloud/l10n`
  src/Components/Announcement.vue
  src/utils/datetime.utils.js
  src/views/Dashboard.vue
Labels: 3. to review
